// <auto-generated />
using System;
using HibaVonal.DataContext.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HibaVonal.DataContext.Migrations
{
    [DbContext(typeof(HibaVonalDBContext))]
    [Migration("20260327161106_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipCost")
                        .HasColumnType("int");

                    b.Property<string>("EquipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IssueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedMaintainerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoomNum")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Urgency")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMaintainerId");

                    b.HasIndex("RoomNum");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("ToolListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToolListId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomNum")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.RoomEquip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomEquips");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ToolListId")
                        .HasColumnType("int");

                    b.Property<string>("ToolSerial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ToolListId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.ToolList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ToolMaker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToolPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ToolLists");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.ToolUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.HasIndex("UserId");

                    b.ToTable("ToolUsers");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<int?>("RoomNum")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomNum");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Equipment", b =>
                {
                    b.HasOne("HibaVonal.DataContext.Entities.Issue", null)
                        .WithMany("Equipments")
                        .HasForeignKey("IssueId");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Issue", b =>
                {
                    b.HasOne("HibaVonal.DataContext.Entities.User", "AssignedMaintainer")
                        .WithMany("AssignedIssues")
                        .HasForeignKey("AssignedMaintainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HibaVonal.DataContext.Entities.Room", "Room")
                        .WithMany("Issues")
                        .HasForeignKey("RoomNum")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedMaintainer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Order", b =>
                {
                    b.HasOne("HibaVonal.DataContext.Entities.ToolList", "ToolList")
                        .WithMany()
                        .HasForeignKey("ToolListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolList");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.RoomEquip", b =>
                {
                    b.HasOne("HibaVonal.DataContext.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HibaVonal.DataContext.Entities.Room", "Room")
                        .WithMany("RoomEquips")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Tool", b =>
                {
                    b.HasOne("HibaVonal.DataContext.Entities.ToolList", "ToolList")
                        .WithMany()
                        .HasForeignKey("ToolListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolList");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.ToolUser", b =>
                {
                    b.HasOne("HibaVonal.DataContext.Entities.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HibaVonal.DataContext.Entities.User", "User")
                        .WithMany("ToolUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.User", b =>
                {
                    b.HasOne("HibaVonal.DataContext.Entities.Room", "Room")
                        .WithMany("Tenants")
                        .HasForeignKey("RoomNum")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Issue", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.Room", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("RoomEquips");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("HibaVonal.DataContext.Entities.User", b =>
                {
                    b.Navigation("AssignedIssues");

                    b.Navigation("ToolUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
